from ratingsys.models import AnnualCode
FH = AnnualCode(rating='FH', Annual_code_Description='Failed,qualify for supplementary/deferred exam')
FH.save()
FK = AnnualCode(rating='FK', Annual_code_Description='Acdemically excluded from the university')
FK.save()
FP = AnnualCode(rating='FP', Annual_code_Description='Not Promoted')
FP.save()
PA = AnnualCode(rating='PA', Annual_code_Description='Qualification Awarded')
PA.save()
PC = AnnualCode(rating='PC', Annual_code_Description='Qualification awarded with Cum Laude')
PC.save()
PG = AnnualCode(rating='PG', Annual_code_Description='Qualify to Graduate')
PG.save()
PH = AnnualCode(rating='PH', Annual_code_Description='Qualification Awarded Posthumous')
PH.save()
PP = AnnualCode(rating='PP', Annual_code_Description='Promoted')
PP.save()
