from ratingsys.models import modulerating

F0 = modulerating(rating='F0', rating_Description='Failed,Special exam granted')
F0.save()
F1 = modulerating(rating='F1', rating_Description='Failed')
F1.save()
F2 = modulerating(rating='F2', rating_Description='Failed, supplimentary granted')
F2.save()
F3 = modulerating(rating='F3', rating_Description='Failed subminimum, supplimentary granted')
F3.save()
F5 = modulerating(rating='F5', rating_Description='Failed supplimentary')
F5.save()
F6 = modulerating(rating='F6', rating_Description='continuing Research subject/module (applicable to M & Ds)')
F6.save()
F7 = modulerating(rating='F7', rating_Description='infrigment of eximantion rules')
F7.save()
F8 = modulerating(rating='F8', rating_Description='Deferred exam granted')
F8.save()
F9 = modulerating(rating='F9', rating_Description='Investigation pending')
F9.save()
FA = modulerating(rating='FA', rating_Description='Failed, no exam addmission')
FA.save()
FC = modulerating(rating='FC', rating_Description='Failed clinicals')
FC.save()
FD = modulerating(rating='FD', rating_Description='Dissertation Outstanding')
FD.save()
FE = modulerating(rating='FE', rating_Description='Failed, re-exam in clincals granted')
FE.save()
FQ = modulerating(rating='FQ', rating_Description='Repeat Block')
FQ.save()
FR = modulerating(rating='FR', rating_Description='Failed subminimum')
FR.save()
FS = modulerating(rating='FS', rating_Description='Failed special exam')
FS.save()
FT = modulerating(rating='FT', rating_Description='absent from class')
FT.save()
FX = modulerating(rating='FX', rating_Description='Failed,Absent from exam')
FX.save()
P1 = modulerating(rating='P1', rating_Description='Passed')
P1.save()
P2 = modulerating(rating='P2', rating_Description='Passed with distinction')
P2.save()
P3 = modulerating(rating='P3', rating_Description='Credit granted')
P3.save()
P4 = modulerating(rating='P4', rating_Description='Passed supplementary')
P4.save()